name: activations
global:
  batch_size: 50
  steps: 25
  epochs: 25
  seed: 75437
  topology: topologies/unet3c.yaml
  optimizer: nadam
  learning_rate: 0.001
  learning_rate_decay: none
  loss: jaccard
  activation: lrelu
  local_response_normalization: 0
  batch_normalization: true
  dropout_rate: 0.5
  initializer: he_normal
  regularizer: none
  constraint: none
  label_weighting: 0.0
dataset:
  train: dataset/medium-256x256-train.tfr
  eval: dataset/medium-256x256-eval.tfr
  test: dataset/medium-256x256-test.tfr
models:
  crelu:
    activation: crelu
  elu:
    activation: elu
  lrelu:
    activation: lrelu
  none:
    activation: none
  relu:
    activation: relu
  relu6:
    activation: relu6
  selu:
    activation: selu
  sigmoid:
    activation: sigmoid
  softmax:
    activation: softmax
  softplus:
    activation: softplus
  softsign:
    activation: softsign
  tanh:
    activation: tanh
